[build]
  command = "prisma generate && bunx next build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  TSC_COMPILE_ON_ERROR = "true"
  ESLINT_NO_DEV_ERRORS = "true"
  DISABLE_ESLINT_PLUGIN = "true"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
